%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 672
image_height: 376
distortion_parameters:
   k1: -0.033552
   k2: 0.001859
   p1: 0.000599
   p2: -0.000901
projection_parameters:
   fx: 269.516269
   fy: 269.734233
   cx: 336.395110
   cy: 188.435176