%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 672
image_height: 376
distortion_parameters:
   k1: -0.033526
   k2: 0.000732
   p1: -0.000028
   p2: -0.001834
projection_parameters:
   fx: 267.974614
   fy: 268.492424
   cx: 331.883269
   cy: 191.786323